---
env:
  contexts:
  - name: "https://ginandjuice.shop"
    urls:
    - "https://ginandjuice.shop"
    includePaths:
    - "https://ginandjuice.shop.*"
    excludePaths: []
    authentication:
      method: "form"
      parameters:
        loginPageUrl: "https://ginandjuice.shop/login"
        loginRequestUrl: "https://ginandjuice.shop/login"
        loginRequestBody: "username={%username%}&password={%password%}"
      verification:
        method: "poll"
        loggedInRegex: "\\QLog out\\E"
        loggedOutRegex: "\\QLog in\\E"
        pollFrequency: 60
        pollUnits: "requests"
        pollUrl: "https://ginandjuice.shop/my-account"
        pollPostData: ""
    sessionManagement:
      method: "cookie"
      parameters: {}
    technology:
      exclude: []
    users:
    - name: "myuser"
      credentials:
        password: "hunter2"
        username: "carlos"
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
    disableAllRules: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters:
    context: "https://ginandjuice.shop"
    user: "myuser"
    url: "https://ginandjuice.shop"
    maxDuration: 0
    maxDepth: 0
    maxChildren: 0
  name: "spider"
  type: "spider"
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
- parameters:
    context: "https://ginandjuice.shop"
    user: "myuser"
    url: "https://ginandjuice.shop"
    maxDuration: 60
    maxCrawlDepth: 10
    numberOfBrowsers: 16
    inScopeOnly: true
    runOnlyIfModern: false
  name: "spiderAjax"
  type: "spiderAjax"
  tests:
  - onFail: "INFO"
    statistic: "spiderAjax.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
- parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters:
    context: "https://ginandjuice.shop"
    user: "myuser"
    policy: ""
    maxRuleDurationInMins: 0
    maxScanDurationInMins: 0
  policyDefinition:
    defaultStrength: "medium"
    defaultThreshold: "medium"
    rules: []
  name: "activeScan"
  type: "activeScan"
- parameters:
    template: "risk-confidence-html"
    reportDir: "C:\\Users\\FabrizioB"
    reportTitle: "ZAP Scanning Report"
    reportDescription: ""
  name: "report"
  type: "report"
