name: DAST API Demo Env

on:
#  pull_request:
#    branches:
#      - master
  workflow_dispatch:

jobs:
  dast:
    runs-on: ubuntu-latest
    #runs-on: ["self-hosted", "EasyBuggy"]
    name: DAST on Prem Testing Action
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.pull_request.head.sha }}
      - name: Checkmarx DAST Github Action
        uses: Checkmarx/dast-github-action@v1.0.4
        env:
          CX_APIKEY: ${{ secrets.AST_API_KEY }}
        with:
          command: api
          config: ${{ github.event.pull_request.head.sha }}/dast-config/zap_config_api.yaml
          openapi: ${{ github.event.pull_request.head.sha }}/dast-config/openapi.yaml
          environment_id: 3527936a-135e-4458-b401-a8817d145d5f
          fail_on: "HIGH"
          log_level: info
          base_url: https://deu.ast.checkmarx.net/
          verbose: true
          output: ${{ github.event.pull_request.head.sha }}/output
      - name: Prepare files
        run: |
          mkdir ./tmp
          sudo cp -r ${{ github.event.pull_request.head.sha }}/output ./tmp
          sudo chown -R runner:runner ./tmp
      - uses: actions/upload-artifact@v3
        if: always()
        name: Upload Logs
        with:
          name: report
          path: ./tmp/output
